version: 2
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
scoops:
  - repository:
      owner: mcwarman
      name: scoop-bucket
      token: "{{ .Env.GH_PUBLIC_REPO_TOKEN }}"
    commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/mcwarman/helm-to-hcl/blob/main/README.md"
    description: "Utility for converting helm configuration to HCL for use in Terraform"
    license: MIT
brews:
  - repository:
      owner: mcwarman
      name: homebrew-tap
    skip_upload: true
    directory: Formula
    homepage: "https://github.com/mcwarman/helm-to-hcl/blob/main/README.md"
    description: "Utility for converting helm configuration to HCL for use in Terraform"
    license: MIT
    test: |
      system "#{bin}/helm-to-hcl", "--version"
