name: release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch all tags
        run: git fetch --force --tags

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          check-latest: true
          cache: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3

      - name: Go Test
        run: go test ./... -race -coverpkg=./... -covermode=atomic -coverprofile=coverage.out

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PUBLIC_REPO_TOKEN: ${{ secrets.GH_PUBLIC_REPO_TOKEN }}

      - name: Bump formulae
        run: ./scripts/homebrew-release.sh
        env:
          GH_PUBLIC_REPO_TOKEN: ${{secrets.GH_PUBLIC_REPO_TOKEN}}
